feat(scripts): check for redis command

diff --git a/tools/run_locally/scripts/macos/at_redis b/tools/run_locally/scripts/macos/at_redis
--- a/tools/run_locally/scripts/macos/at_redis
+++ b/tools/run_locally/scripts/macos/at_redis
@@ -18,5 +18,10 @@ echo "Running $scriptDir/$scriptName in working directory $(pwd)"
 # We need to run a redis server, with a password required.
 # (Un-comment "requirepass foobared" in redis.conf)
 
+if ! command -v redis-server >/dev/null 2>&1; then
+  echo "redis-server not found."
+  echo "  brew install redis"
+  exit 1
+fi
 echo "Starting redis server"
 redis-server /usr/local/etc/redis.conf
