test: Further changes for cicd VM tests

diff --git a/.github/workflows/at_server.yaml b/.github/workflows/at_server.yaml
--- a/.github/workflows/at_server.yaml
+++ b/.github/workflows/at_server.yaml
@@ -613,43 +613,39 @@ jobs:
         run: dart test --concurrency=1
 
       # Don't delete atServers whilst we're debugging
-      # - name: Delete atSigns
-      #   if: always() # Always try to clear up atSigns even if an earlier step has failed.
-      #   env:
-      #     AT_SIGN_1: ${{ steps.atsign_names.outputs.AT_SIGN_1 }}
-      #     AT_SIGN_2: ${{ steps.atsign_names.outputs.AT_SIGN_2 }}
-      #   run: |
-      #     delete_atSign() {
-      #       curl -s --location --request POST 'https://infrastructure-api-b.dev.atsign.cloud/api/infrastructure/delete' \
-      #       --header 'Authorization: ${{secrets.NODE_API_DELETE}}' \
-      #       --header 'Content-Type: application/json' \
-      #       --data-raw '{
-      #           "atsign" : "'$1'"
-      #       }'
-      #     }
-      #     delete_atSign "$AT_SIGN_1"
-      #     delete_atSign "$AT_SIGN_2"
-
-      # - name: Check that atSigns have been deleted
-      #   env:
-      #     AT_SIGN_1: ${{ steps.atsign_names.outputs.AT_SIGN_1 }}
-      #     AT_SIGN_2: ${{ steps.atsign_names.outputs.AT_SIGN_2 }}
-      #   # TODO if this step fails then it should do a gChat notification rather than exit 1
-      #   # TODO this only checks that entry has been removed from root
-      #   run: |
-      #     sleep 20
-      #     AT_SIGN_1_HOST_RESP=$((echo $AT_SIGN_1; sleep 1) | openssl s_client -connect root.atsign.wtf:64 2>/dev/null | grep --color=none "^@.*:" | cut -d'@' -f2)
-      #     AT_SIGN_2_HOST_RESP=$((echo $AT_SIGN_2; sleep 1) | openssl s_client -connect root.atsign.wtf:64 2>/dev/null | grep --color=none "^@.*:" | cut -d'@' -f2)
-      #     if [ -z "$AT_SIGN_1_HOST_RESP" ] && [ -z "$AT_SIGN_2_HOST_RESP" ]; then
-      #       echo "atSigns deleted successfully"
-      #     else
-      #       echo "atSigns still exist"
-      #       exit 1
-      #     fi
-
-      - name: Deliberately fail so that we can re-run
+      - name: Delete atSigns
+        if: always() # Always try to clear up atSigns even if an earlier step has failed.
+        env:
+          AT_SIGN_1: ${{ steps.atsign_names.outputs.AT_SIGN_1 }}
+          AT_SIGN_2: ${{ steps.atsign_names.outputs.AT_SIGN_2 }}
         run: |
-          exit 1
+          delete_atSign() {
+            curl -s --location --request POST 'https://infrastructure-api-b.dev.atsign.cloud/api/infrastructure/delete' \
+            --header 'Authorization: ${{secrets.NODE_API_DELETE}}' \
+            --header 'Content-Type: application/json' \
+            --data-raw '{
+                "atsign" : "'$1'"
+            }'
+          }
+          delete_atSign "$AT_SIGN_1"
+          delete_atSign "$AT_SIGN_2"
+
+      - name: Check that atSigns have been deleted
+        env:
+          AT_SIGN_1: ${{ steps.atsign_names.outputs.AT_SIGN_1 }}
+          AT_SIGN_2: ${{ steps.atsign_names.outputs.AT_SIGN_2 }}
+        # TODO if this step fails then it should do a gChat notification rather than exit 1
+        # TODO this only checks that entry has been removed from root
+        run: |
+          sleep 20
+          AT_SIGN_1_HOST_RESP=$((echo $AT_SIGN_1; sleep 1) | openssl s_client -connect root.atsign.wtf:64 2>/dev/null | grep --color=none "^@.*:" | cut -d'@' -f2)
+          AT_SIGN_2_HOST_RESP=$((echo $AT_SIGN_2; sleep 1) | openssl s_client -connect root.atsign.wtf:64 2>/dev/null | grep --color=none "^@.*:" | cut -d'@' -f2)
+          if [ -z "$AT_SIGN_1_HOST_RESP" ] && [ -z "$AT_SIGN_2_HOST_RESP" ]; then
+            echo "atSigns deleted successfully"
+          else
+            echo "atSigns still exist"
+            exit 1
+          fi
 
   # This job runs on trigger event 'push' to trunk branch.
   # The job builds the staging version of at_virtual_env and pushes the image to docker hub.
